folder=star20-AF-EH-GS-FG-GC-NN-EG-PC-HL-TA-EM-CC-SM-CB-PL-PA-PP-AP-EC-OH

rm 16-translatorx_out/$folder/*1.fasta_out*html
rm 16-translatorx_out/$folder/*2.fasta_out*html
rm 16-translatorx_out/$folder/*3.fasta_out*html
rm 16-translatorx_out/$folder/*4.fasta_out*html
rm 16-translatorx_out/$folder/*5.fasta_out*html
rm 16-translatorx_out/$folder/*6.fasta_out*html
rm 16-translatorx_out/$folder/*7.fasta_out*html
rm 16-translatorx_out/$folder/*8.fasta_out*html
rm 16-translatorx_out/$folder/*.fasta_out*html
rm 16-translatorx_out/$folder/*1.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*2.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*3.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*4.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*5.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*6.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*7.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*8.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*.fasta_out*aaseqs*
rm 16-translatorx_out/$folder/*1.fasta_out*nt1*
rm 16-translatorx_out/$folder/*2.fasta_out*nt1*
rm 16-translatorx_out/$folder/*3.fasta_out*nt1*
rm 16-translatorx_out/$folder/*4.fasta_out*nt1*
rm 16-translatorx_out/$folder/*5.fasta_out*nt1*
rm 16-translatorx_out/$folder/*6.fasta_out*nt1*
rm 16-translatorx_out/$folder/*7.fasta_out*nt1*
rm 16-translatorx_out/$folder/*8.fasta_out*nt1*
rm 16-translatorx_out/$folder/*.fasta_out*nt1*
rm 16-translatorx_out/$folder/*1.fasta_out*nt2*
rm 16-translatorx_out/$folder/*2.fasta_out*nt2*
rm 16-translatorx_out/$folder/*3.fasta_out*nt2*
rm 16-translatorx_out/$folder/*4.fasta_out*nt2*
rm 16-translatorx_out/$folder/*5.fasta_out*nt2*
rm 16-translatorx_out/$folder/*6.fasta_out*nt2*
rm 16-translatorx_out/$folder/*7.fasta_out*nt2*
rm 16-translatorx_out/$folder/*8.fasta_out*nt2*
rm 16-translatorx_out/$folder/*.fasta_out*nt2*
rm 16-translatorx_out/$folder/*1.fasta_out*nt3*
rm 16-translatorx_out/$folder/*2.fasta_out*nt3*
rm 16-translatorx_out/$folder/*3.fasta_out*nt3*
rm 16-translatorx_out/$folder/*4.fasta_out*nt3*
rm 16-translatorx_out/$folder/*5.fasta_out*nt3*
rm 16-translatorx_out/$folder/*6.fasta_out*nt3*
rm 16-translatorx_out/$folder/*7.fasta_out*nt3*
rm 16-translatorx_out/$folder/*8.fasta_out*nt3*
rm 16-translatorx_out/$folder/*.fasta_out*nt3*
rm 16-translatorx_out/$folder/*1.fasta_out*log
rm 16-translatorx_out/$folder/*2.fasta_out*log
rm 16-translatorx_out/$folder/*3.fasta_out*log
rm 16-translatorx_out/$folder/*4.fasta_out*log
rm 16-translatorx_out/$folder/*5.fasta_out*log
rm 16-translatorx_out/$folder/*6.fasta_out*log
rm 16-translatorx_out/$folder/*7.fasta_out*log
rm 16-translatorx_out/$folder/*8.fasta_out*log
rm 16-translatorx_out/$folder/*.fasta_out*log
rm 16-translatorx_out/$folder/*1.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*2.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*3.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*4.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*5.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*6.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*7.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*8.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*.fasta_out*aa_ali*
rm 16-translatorx_out/$folder/*html
rm 16-translatorx_out/$folder/*aaseqs.1*
rm 16-translatorx_out/$folder/*aaseqs.2*
rm 16-translatorx_out/$folder/*aaseqs*
rm 16-translatorx_out/$folder/*nt3*
rm 16-translatorx_out/$folder/*nt2*
rm 16-translatorx_out/$folder/*nt1*
rm 16-translatorx_out/$folder/*log
rm 16-translatorx_out/$folder/*aa_ali*
